# Generated by Django 2.2.16 on 2022-06-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='Rfi1SG7LAH', max_length=10, verbose_name='код подтверждения'),
        ),
    ]
