# Generated by Django 2.2.16 on 2022-06-22 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Текст', 'verbose_name_plural': 'Текст'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Текст', 'verbose_name_plural': 'Текст'},
        ),
    ]
