# Generated by Django 2.2.16 on 2022-06-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220618_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='SkcHqWwrVf', max_length=10, verbose_name='код подтверждения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ANON', 'Anonymous'), ('USER', 'user'), ('MOD', 'Moderator'), ('ADM', 'Admin')], default='USER', max_length=4),
        ),
    ]
