# Generated by Django 2.2.16 on 2022-06-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220620_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='ntA8Exz5JE', max_length=10, verbose_name='код подтверждения'),
        ),
    ]
