# Generated by Django 2.2.16 on 2022-06-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220618_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='TNj2QXyR8Z', max_length=10, verbose_name='код подтверждения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ANON', 'anonymous'), ('USER', 'user'), ('MOD', 'moderator'), ('ADM', 'admin')], default='USER', max_length=4),
        ),
    ]
