# Generated by Django 2.2.16 on 2022-06-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220619_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titles',
            old_name='achievements',
            new_name='genres',
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='oeOpLGUK4v', max_length=10, verbose_name='код подтверждения'),
        ),
    ]
