# Generated by Django 2.2.16 on 2022-06-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220625_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(unique=True, verbose_name='Оценка'),
        ),
    ]
