# Generated by Django 2.2.16 on 2022-06-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20220619_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='27Dn4x5Un4', max_length=10, verbose_name='код подтверждения'),
        ),
    ]
