# Generated by Django 2.2.16 on 2022-06-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20220619_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titles',
            old_name='genres',
            new_name='genre',
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='HDTvFEc3GM', max_length=10, verbose_name='код подтверждения'),
        ),
    ]
