# Generated by Django 2.2.16 on 2022-06-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20220620_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='bd0TUm8b9P', max_length=10, verbose_name='код подтверждения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ANON', 'Anonymous'), ('USER', 'User'), ('MOD', 'Moderator'), ('admin', 'Admin')], default='USER', max_length=4),
        ),
    ]
