# Generated by Django 2.2.16 on 2022-06-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20220620_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='UGMiEhibxI', max_length=10, verbose_name='код подтверждения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ANON', 'Anonymous'), ('user', 'User'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='user', max_length=4),
        ),
    ]
